---
- name: copy a file
  hosts: all
  become: true
  tasks:
    - ansible.builtin.copy:
       -  src: /home/ansadmin/ansible_learning/index.html
          dest: /home/ansadmin
          owner: john
          mode: 0600
