---
- name: yum module
  hosts: webservers
  become: true
  tasks:
  - name: installing httpd server
    yum:
      name: httpd
      state: installed

  - name: starting a service
    ansible.builtin.service:
      name: httpd
      state: started
